export const projectsData = [
  {
    id: 1,
    title: "The Serenity Villa",
    slug: "the-serenity-villa",
    location: "Banana Island, Lagos",
    price: "₦850,000,000",
    type: "5 Bed Detached",
    image:
      "https://plus.unsplash.com/premium_photo-1686090449192-4ab1d00cb735?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    overview: {
      beds: "5 Bedroom Smart Terrace Duplex",
      status: "Carcass Level (Unfinished Interior)",
      propertyType: "Buy & Build",
      size: "450 sqm",
    },
    features: [
      "Strategic Location: Banana Island, Lagos",
      "Within minutes from major expressways",
      "Quick access to city center and major landmarks",
      "Proximity to estates, shopping plazas, schools, and key infrastructure",
      "Smart Home-Ready Design: Layout optimized for smart home integration",
      "Customizable Finishing: Delivered at carcass level to choose your interior materials",
      "Prime Residential Corridor: Banana Island is highly sought after",
      "FCDA-Compliant and Secure: Situated in a planned estate environment",
    ],
    videoPlaceholder: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80",
    description: "This is ideal for discerning buyers who want to customize their finishes while saving significantly on upfront costs. The Serenity Villa is not just another housing project; it's your chance to build a personalized smart home in a growing, well-connected part of Lagos.",
  },
  {
    id: 2,
    title: "Nova Luxury Apartments",
    slug: "nova-luxury-apartments",
    location: "Ikoyi, Lagos",
    price: "₦420,000,000",
    type: "4 Bed Penthouse",
    image:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80",
    overview: {
      beds: "4 Bedroom Penthouse Suite",
      status: "Fully Finished",
      propertyType: "Move-In Ready",
      size: "320 sqm",
    },
    features: [
      "Panoramic skyline views of Ikoyi",
      "Dedicated high-speed elevator access",
      "Private rooftop terrace with plunge pool",
      "Integrated home automation system",
      "Italian marble flooring throughout living areas",
      "Chef's kitchen with built-in Miele appliances",
      "24/7 concierge and premium security",
    ],
    videoPlaceholder: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80",
    description: "Experience the pinnacle of urban luxury at Nova Luxury Apartments. Boasting sweeping views and meticulous contemporary design, this penthouse offers an unmatched lifestyle in the heart of Ikoyi.",
  },
  {
    id: 3,
    title: "The Haven",
    slug: "the-haven",
    location: "Lekki Phase 1, Lagos",
    price: "₦250,000,000",
    type: "4 Bed Terraced",
    image:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80",
    overview: {
      beds: "4 Bedroom Terraced House",
      status: "Off-Plan",
      propertyType: "Investment / Residential",
      size: "280 sqm",
    },
    features: [
      "Located in a highly secure gated community",
      "Contemporary minimalist architecture",
      "Spacious en-suite bedrooms with walk-in closets",
      "Dedicated parking for 3 vehicles",
      "Communal swimming pool and fitness center",
      "Solar power and inverter ready",
      "Flexible payment plans available",
    ],
    videoPlaceholder: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80",
    description: "The Haven brings modern terraced living to Lekki Phase 1. Designed for families and professionals alike, these homes strike the perfect balance between communal luxury and private tranquility.",
  },
];
